apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flood-api
  template:
    metadata:
      labels:
        app: flood-api
    spec:
      containers:
      - image: ghcr.io/openearthplatforminitiative/flood-api:0.2.0
        name: flood-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flood-api-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: flood-api
