apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood-api
  namespace: apps-flood-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flood-api
  template:
    metadata:
      namespace: apps-flood-api
      labels:
        app: flood-api
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/flood-api:0.5.4
          name: flood-api
          ports:
            - containerPort: 8080
          env:
            - name: API_ROOT_PATH
              value: "/flood"
            - name: VERSION
              value: 0.5.4
---
apiVersion: v1
kind: Service
metadata:
  name: flood-api
  namespace: apps-flood-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: flood-api
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: flood-api
spec:
  http:
    - name: flood-api
      match:
        paths:
          - /flood/*
      backends:
        - serviceName: flood-api
          servicePort: 80
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/flood/(.*)"
              - "/$1"
