apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood-api
  namespace: apps-flood-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flood-api
  template:
    metadata:
      namespace: apps-flood-api
      labels:
        app: flood-api
    spec:
      containers:
      - image: ghcr.io/openearthplatforminitiative/flood-api:0.5.0
        name: flood-api
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: 0.5.0
---
apiVersion: v1
kind: Service
metadata:
  name: flood-api
  namespace: apps-flood-api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: flood-api
